### ISSUE TITLE
ixset missing from stackage LTS 9

### ISSUE THREAD

**Issue by cdupont** [Happstack/ixset#1]
Hi,
I can see that ixset is missing from stackage LTS version 9:
https://www.stackage.org/lts-9.5
It was there in version 8.
Do you know what is the issue?
Thanks

**Comment by ddssff** [comment]
I don't know what the issue is.

**Comment by stepcut** [comment]
Keeping things in stackage requires someone who is passionate about the stackage process. We currently have no one who has volunteered to keep on top of that process.
